[tool.uv]
cache-dir = "./.uv_cache"

[project]
name = "Studentprognose"
version = "0.1.0"
description = "Studentprognose, prediction of student numbers in the following (and upcoming) year(s)."
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.2",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "statsmodels>=0.14.5",
    "xgboost>=3.0.5",
    "xlsxwriter>=3.2.9",
    "openpyxl>=3.1.2",
]

[tool.uv.build-backend]
module-root = ""
module-name = "scripts"

[project.scripts]
individual = "scripts.models.individual_mbo:main"
main = "scripts.main:main"
clear_cache = "scripts.clear_cache:main"
evaluation = "scripts.utils.evaluation:main"

# Add this section to guide package discovery
[tool.setuptools.packages.find]
include = ["scripts*"] 

